### PR TITLE
Fix interface cleanup

### PR DESCRIPTION
**Pull request by ljkiraly**
Move any orphan nsm interface to host namespace and delete it.

Related issue: networkservicemesh/deployments-k8s#9778

### CODE REVIEW

**Comment by ljkiraly** [comment]
Changed call order as @glazychev-art suggested in https://github.com/networkservicemesh/sdk-ovs/pull/275#issuecomment-1784658463

**Review by glazychev-art — APPROVED** [review]

**Comment by ljkiraly** [comment]
@denis-tingaikin  I verified manually running  Kernel2Kernel, Kernel2IP2Kernel, feature tests and local_forwarder_death, remote_forwarder_death healing tests with forwarder-ovs. 

I did not verified forwarder-sriov. That might be affected by these changes.

**Comment by denis-tingaikin** [comment]
@ljkiraly OK, perfect. 

We're planning to release v1.11.1-RC.2 on Monday. Are these fixes urgent for you? Can we merge this PR right **after** v1.11.1?

**Comment by ljkiraly** [comment]
@denis-tingaikin Not so urgent, can wait after release.

**Review by denis-tingaikin — APPROVED** [review]

**Pull request merged**
