### PR TITLE
Fix for Policy Base Routing failure; Possible table ID collision.

### PR DESCRIPTION
**Pull request by ljkiraly**
Related issue: networkservicemesh/deployments-k8s/issues/9119

Added mutex lock to protect table ID selection from parallel runs.

### CODE REVIEW

**Review by denis-tingaikin — COMMENTED** [review]
Question: 

Is NSC from your usecase requests two or more connections?

**Comment by ljkiraly** [comment]
@denis-tingaikin In the use case described in the issue (networkservicemesh/deployments-k8s/issues/9119) the NSC has 2 connections and each nsc interface has 2 IP's. So that's why needs 2+2 source route and 4 tables.

**Comment by denis-tingaikin** [comment]
@ljkiraly Got it. I think we need to solve the issue with multiple connections for NSC within `begin` chain element https://github.com/networkservicemesh/sdk/tree/main/pkg/networkservice/common/begin.

For now, could you try to use the same first path id for the client?


I meen something like this:

```go
var req1, req2 networkservice.Request

nsmClient := client.NewClient(...)


conn1, _ := nscClient.Request(ctx, req1)

req2.GetConnection().GetPath().PathSegemets = append(conn1.GetPath().PathSegments[0])

conn2, _ := nscClient.Request(ctx, req2)
```

Then all operations for the client will be invoked in queue on the server. See at https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/begin/doc.go#L18-L102

**Comment by ljkiraly** [comment]
@denis-tingaikin OK I see your point now. Other than that my proposal wasn't good enough in case of multiple NSCs on the same node. There is no sense to block the forwarder at the point where collecting the existing routing table IDs, This routing information is set to a given NSC namespace, so can not collide to another NSCs.

I can accept the answer provided by @NikitaSkrynnik (option 2: Two requests can go in parallel, but the first path segment should be the same in both of them)

**Pull request closed without merging**
