### PR TITLE
Policy Based Routing dynamic dst address

### PR DESCRIPTION
**Pull request by yuraxdrumz**
Hey,

I have a use case where I need to use Policy Based Routing to allow an NSC to pass all of its TCP, UDP and ICMP traffic through NSM.

While using 1 NSC everything worked fine. I had an NSE with a `10.12.1.0/24` CIDR and I knew NSC always gets dst address of `10.12.1.0` to reach the NSE.

After adding several other NSC's, I noticed each NSC gets a different DST address, for example:

* NSC1 -> SRC (10.12.1.1), NSE DST (10.12.1.0)
* NSC2 -> SRC (10.12.1.3), NSE DST (10.12.1.2)
* NSC3 -> SRC (10.12.1.5), NSE DST (10.12.1.4)

I saw you have a feature called `Topologically Aware Endpoint Selection` that allows replacing `nodeName` dynamically, so I used the same idea here.

I passed the dst ip from `conn.GetContext().GetIpContext().GetDstIpAddrs()` to the `create` function.

I also added a DST_ADDRESS keyword, that if it exists, will be replaced by the dst ip from above.

Example of PBR config map file with this feature:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-config-file
data:
  config.yaml: |
    - proto: 6
      routes:
        - prefix: 0.0.0.0/0
          nexthop: DST_ADDRESS
    - proto: 1
      routes:
        - prefix: 0.0.0.0/0
          nexthop: DST_ADDRESS
    - proto: 17
      routes:
        - prefix: 0.0.0.0/0
          nexthop: DST_ADDRESS
```

This was tested with a custom compiled forwarder-vpp.

If you have a different idea of how to implement this or some integration tests that need to implemented / added / modified that I overlooked, please tell me and I will gladly add them.

Thanks

### CODE REVIEW

**Comment by glazychev-art** [comment]
Thanks for the report!
Can you please tell if your script doesn't work if you don't specify `nexthop` it at all?

If you need it anyway, I think we need to look at the NSE side.. It contains the `policyroute` chain-element - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/policyroute/server.go

The moment we put policies into context, we already know Src/DstIpAddresses. So, we can iterate over policy routes and add nextHop if it is empty.
It will look something like this
```
...
		for _, route := range p.Routes {
			if route.NextHop == "" {
				ip, _, err := net.ParseCIDR(ipContext.DstIpAddrs[0])
				if err != nil {
					return nil, err
				}
				route.NextHop = ip.String()
			}
		}
...
```
Add it to this cycle: https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/policyroute/server.go#L55
So you don't have to use `nexthop: DST_ADDRESS`
What do you think?

**Comment by yuraxdrumz** [comment]
Hello @glazychev-art 

I kept BC for the feature, if next hop does not exist `via x.x.x.x` will not be added and ARP requests will be sent through the nsm interface.

But it does make more sense to do it on NSE side, and add next hop as NSE by default when no next hop exists.

I will open a PR for sdk

Thanks

**Comment by yuraxdrumz** [comment]
@glazychev-art 

Ok, so I checked what you suggested.

I encountered a problem when using several NSC's due to policy getter being called only once and stored in memory.

Example:

NSC1 (src: 169.254.0.1) -> NSE - (src: 169.254.0.0) - no next hop, so store next hop = 169.254.0.0
NSC2 (src: 169.254.0.3) -> NSE - (src: 169.254.0.2) - next hop exists so dont do anything and next hop stays 169.254.0.0

on the 2nd NSC and above, next hop should be per dst ip like you suggested, but for that to happen we have several options:

- Create map and store mapping of NSC -> Policies
- Read FS for every .Request and we can remove the need for fs.Watch - this is a bit ugly due to fs access on every request

What do you think?

**Comment by glazychev-art** [comment]
@yuraxdrumz 
Ah.. got it.
I think the reason is that we are passing data using pointers - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/policyroute/server.go#L54
`getPolicies` is implemented here - https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go#L391
I think that the `func Get()` should return a copy of the policies. Then the first NSC will not affect the others.

By the way, I was wrong, adding nextHop should not be in this loop.. - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/policyroute/server.go#L55
We need to get the policies, update them (add nextHop), and then set them to the ipContext.

**Pull request closed without merging**
